export const BEGIN_FETCH = "BEGIN_FETCH";

export const FETCH_SUCCESS = "FETCH_SUCCESS";

export const FETCH_FAILURE = "FETCH_FAILURE";

export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";

export const UPLOAD_FAILURE = "UPLOAD_FAILURE";

export const INVALID_ANSWER = "INVALID_ANSWER";

export const DELETE_SUCCESS = "DELETE_SUCCESS";

export const DELETE_FAILURE = "DELETE_FAILURE";

export const UPDATE_SUCCESS = "UPDATE_SUCCESS";

export const UPDATE_FAILURE = "UPDATE_FAILURE";